server:
  port: 8888

spring:
  application:
    name: tecna-gateway
  cloud:
    gateway:
      routes:
        - id: tecna-groovy-rest-api
          uri: lb://TECNA-GROOVY-REST-API
          predicates:
            - Path=/api/**
        - id: tecna-groovy-rest-api
          uri: lb://TECNA-GROOVY-REST-API
          predicates:
            - Path=/api/groovyrunner/**
      discovery:
        locator:
          enabled: true

info:
  app:
    name: ${spring.application.name}

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
    healthcheck:
      enabled: true
  instance:
    instance-id: ${spring.application.name}:${random.value}
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 2


management:
  endpoints:
    web:
      exposure:
        include:
          - mappings
          - env
          - health
          - info
springdoc:
  api-docs:
    enabled: true
  show-actuator: true
